# Generated by Django 5.2.7 on 2025-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_rol_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('chofer', 'Chofer'), ('operario_carga', 'Operario de Carga y Descarga'), ('encargado', 'Encargado'), ('personal_limpieza', 'Personal de Limpieza'), ('operaria_lavanderia', 'Operaria de Lavandería'), ('cajero', 'Cajero')], default='empleado', max_length=30),
        ),
    ]
