# Generated by Django 5.2.7 on 2025-11-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_perfil_failed_login_attempts_for_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('chofer', 'Chofer'), ('operario_carga', 'Operario de Carga y Descarga'), ('encargado', 'Encargado'), ('cajero', 'Cajero')], default='empleado', max_length=20),
        ),
    ]
