# Generated by Django 5.2.7 on 2025-10-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_alter_alquiler_cliente_alter_detalquiler_cantidad_and_more'),
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'ordering': ['-creado_en', 'id']},
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cliente_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmado', 'confirmado'), ('cancelado', 'cancelado'), ('entregado', 'entregado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alquiler', to='pedidos.pedido'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('incidente', 'Incidente'), ('otro', 'Otro')], default='incidente', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('comprobante_url', models.URLField(blank=True)),
                ('comprobante_file', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.pedido')),
            ],
        ),
    ]
