# Generated by Django 5.2.7 on 2025-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_alter_alquiler_options_alquiler_cliente_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='garantia_estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('devuelta', 'devuelta'), ('descontada', 'descontada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_fecha_cobro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_metodo',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_nota',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
