# Generated by Django 5.2.6 on 2025-11-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0004_alquiler_garantia_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
