# Generated by Django 5.2.7 on 2025-11-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0005_delete_pago'),
        ('clientes', '0001_initial'),
        ('pedidos', '0002_pedido_garantia_descuento_pedido_garantia_dni_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='alquiler',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de garantía cobrado (se copia desde pedido.garantia_monto)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='cliente_fk',
            field=models.ForeignKey(blank=True, help_text='Cliente del alquiler', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='garantia_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('devuelta', 'Devuelta'), ('aplicada', 'Aplicada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='garantia_monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECADO] Usar garantia_monto', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='pedido',
            field=models.OneToOneField(blank=True, help_text='Pedido que generó este alquiler', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alquiler', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='origen',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('demora', 'Demora en devolución'), ('otro', 'Otro')], default='incidente', max_length=20),
        ),
    ]
