# Generated by Django 5.2.7 on 2025-10-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre', 'id']},
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
