# Generated by Django 5.2.7 on 2025-11-12 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('monto_inicial_efectivo', models.DecimalField(decimal_places=2, default=0, help_text='Dinero en efectivo al abrir', max_digits=12)),
                ('monto_inicial_transferencia', models.DecimalField(decimal_places=2, default=0, help_text='Dinero en banco/transferencias al abrir', max_digits=12)),
                ('monto_final_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('monto_final_transferencia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('diferencia_transferencia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('notas_apertura', models.TextField(blank=True)),
                ('notas_cierre', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(help_text='Cajero/Empleado a cargo de esta caja', on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='empleados.empleado')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCaja',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('APERTURA', 'Apertura de caja'), ('CIERRE', 'Cierre de caja'), ('PAGO_REGISTRADO', 'Pago registrado'), ('AJUSTE', 'Ajuste manual'), ('NOTA', 'Nota/Observación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='caja.caja')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
