# Generated by Django 5.2.7 on 2025-10-27 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0003_alter_producto_options_producto_stock_reservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('confirmado', 'confirmado'), ('cancelado', 'cancelado'), ('entregado', 'entregado')], default='pendiente', max_length=20)),
                ('fecha_hora_evento', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('senia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pago', models.CharField(blank=True, max_length=40)),
                ('comprobante_url', models.URLField(blank=True)),
                ('comprobante_file', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('productos', models.ManyToManyField(blank=True, related_name='pedidos', through='pedidos.DetPedido', to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
    ]
