# Generated by Django 5.2.7 on 2025-10-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='garantia_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_dni_file',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/garantia/dni/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_dni_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('devuelta', 'devuelta'), ('descontada', 'descontada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_otro_file',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/garantia/otro/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_otro_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_serv_file',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/garantia/servicio/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_serv_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garantia_tipo',
            field=models.CharField(choices=[('dni', 'dni'), ('servicio', 'servicio'), ('otro', 'otro')], default='dni', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprobante_file',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/senia/'),
        ),
    ]
