# Generated by Django 5.2.7 on 2025-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_garantia_descuento_pedido_garantia_dni_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_evento',
            field=models.CharField(blank=True, help_text='Dirección donde se hace el evento / entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retira en el local'), ('envio', 'Envío a domicilio')], default='retiro', help_text='Si el cliente retira o se entrega a domicilio', max_length=20),
        ),
    ]
