# Generated by Django 5.2.7 on 2025-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_direccion_evento_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencia_entrega',
            field=models.CharField(blank=True, help_text='Referencia adicional para la entrega (piso, depto, etc.)', max_length=255),
        ),
    ]
