# Generated by Django 5.2.7 on 2025-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_referencia_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
