# Generated by Django 5.2.7 on 2025-11-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_costo_flete_pedido_zona_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='zona_entrega',
        ),
    ]
