# Generated by Django 5.2.6 on 2025-11-09 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0005_delete_pago'),
        ('clientes', '0001_initial'),
        ('pedidos', '0002_pedido_garantia_descuento_pedido_garantia_dni_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('SENIA', 'Seña / Anticipo'), ('GARANTIA', 'Garantía'), ('SALDO', 'Pago de saldo'), ('OTRO', 'Otro')], default='SALDO', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('comprobante_pago', models.CharField(blank=True, help_text='Número de comprobante / referencia externa / URL.', max_length=255)),
                ('estado_garantia', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('DEVUELTA', 'Devuelta al cliente'), ('APLICADA', 'Aplicada a daños')], max_length=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alquileres.alquiler')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='clientes.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
