# Generated by Django 5.2.7 on 2025-11-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0005_delete_pago'),
        ('clientes', '0001_initial'),
        ('pagos', '0001_initial'),
        ('pedidos', '0002_pedido_garantia_descuento_pedido_garantia_dni_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago', '-id_pago']},
        ),
        migrations.AddField(
            model_name='pago',
            name='sentido',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='alquileres.alquiler'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_garantia',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('DEVUELTA', 'Devuelta'), ('APLICADA', 'Aplicada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='notas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('SENIA', 'Seña / Anticipo'), ('SALDO', 'Saldo'), ('GARANTIA', 'Garantía cobrada'), ('DEVOLUCION_GARANTIA', 'Devolución garantía'), ('APLICACION_GARANTIA', 'Garantía aplicada a daños'), ('OTRO_INGRESO', 'Otro ingreso'), ('OTRO_EGRESO', 'Otro egreso')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='pago',
            table=None,
        ),
    ]
