# Generated by Django 5.2.7 on 2025-11-12 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('pagos', '0002_alter_pago_options_pago_sentido_alter_pago_alquiler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='caja',
            field=models.ForeignKey(blank=True, help_text='Caja en la que se registró este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.caja'),
        ),
    ]
