# Generated by Django 5.2.7 on 2025-11-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_caja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago', '-id_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('SENIA', 'Seña / Anticipo'), ('SALDO', 'Saldo'), ('GARANTIA', 'Garantía cobrada'), ('DEVOLUCION_TARDIA', 'Cobro por devolución tardía'), ('OTRO_INGRESO', 'Otro ingreso'), ('DEVOLUCION_GARANTIA', 'Devolución garantía'), ('APLICACION_GARANTIA', 'Garantía aplicada a daños'), ('OTRO_EGRESO', 'Otro egreso')], max_length=30),
        ),
    ]
