# Generated by Django 5.2.7 on 2025-11-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('pagos', '0004_alter_pago_options_alter_pago_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.caja'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('ALQUILER', 'Pago de Alquiler'), ('COMPRA_INSUMOS', 'Compra de Insumos'), ('PAGO_TRABAJADORES', 'Pago a Trabajadores'), ('SERVICIOS', 'Servicios'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRO_MOVIMIENTO', 'Otro Movimiento'), ('SENIA', 'Seña / Anticipo'), ('SALDO', 'Saldo'), ('GARANTIA', 'Garantía cobrada'), ('DEVOLUCION_TARDIA', 'Cobro por devolución tardía'), ('OTRO_INGRESO', 'Otro ingreso'), ('DEVOLUCION_GARANTIA', 'Devolución garantía'), ('APLICACION_GARANTIA', 'Garantía aplicada a daños'), ('OTRO_EGRESO', 'Otro egreso')], max_length=30),
        ),
    ]
