# Generated by Django 5.2.6 on 2025-11-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0004_alquiler_garantia_estado_and_more'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateTimeField()),
                ('direccion', models.CharField(max_length=255)),
                ('estado_entrega', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='alquileres.alquiler')),
                ('responsable_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_responsable', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_hora_entrega', '-id_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetEntrega',
            fields=[
                ('id_det_entregas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.PositiveIntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrega', to='empleados.empleado')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entregas.entrega')),
            ],
            options={
                'verbose_name': 'Detalle de entrega',
                'verbose_name_plural': 'Detalles de entregas',
            },
        ),
    ]
