# Generated by Django 5.2.6 on 2025-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha_hora_entrega_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
